import { readFile } from 'fs/promises';
import { ValidationError } from '@/lib/errors/validation-error';
import { join } from 'path';
import { getPipelineDirectory } from './directory';

let cachedPipelines: string[] | null = null;

/**
 * Load reserved pipelines from cache file
 * The cache file is generated by the Go backend from GitHub on init
 */
async function loadReservedPipelines(): Promise<string[]> {
  if (cachedPipelines !== null) {
    return cachedPipelines;
  }

  try {
    const pipelineDir = await getPipelineDirectory('package');
    const cacheFile = join(pipelineDir, 'reserved_pipelines.txt');
    const content = await readFile(cacheFile, 'utf-8');

    const pipelines = content
      .split('\n')
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('#'));

    cachedPipelines = pipelines;
    return cachedPipelines;
  } catch (error) {
    // The cache file should have been created by the Go backend on init, if
    // it wasn't then we should be erroring to prevent a user from creating
    // a pipeline that will fail to build.
    throw new ValidationError(
      'Reserved pipeline cache file missing or unreadable'
    );
  }
}

/**
 * Check if a path is reserved by melange
 *
 * @param path - The pipeline path to check (e.g., "go/build")
 * @returns Promise<boolean> - true if reserved, false if not reserved
 * @throws ValidationError if the reserved pipeline validation system is unavailable
 */
export async function isReservedPipeline(path: string): Promise<boolean> {
  try {
    const pipelines = await loadReservedPipelines();
    return pipelines.includes(path);
  } catch (error) {
    // Re-throw as ValidationError for user-facing pipeline validation
    throw new ValidationError(
      `Cannot validate pipeline path "${path}" - reserved pipeline cache file missing or unreadable`
    );
  }
}

