package buildgraph

import (
	"container/list"
	"sort"
)

// ============================================================
// Public API – explicit build DAG
// ============================================================

// Edge represents a “must-happen-before” constraint between two build nodes.
// Node IDs are strings generated by BuildDAG (see nodeID function).
// For example, an Edge{From: "b", To: "c"} means that the first build of "b"
// must complete before the first build of "c" can begin.
//
// If the graph contains cycles, BuildDAG introduces a second pass for each
// package in the cycle using the suffix "#2" and adds an edge from "pkg" to
// "pkg#2". Callers may ignore nodes with the “#2” suffix if their build system
// handles cycles differently.
//
// Both the returned `nodes` slice and `edges` slice are deterministic, with
// stable ordering across runs for the same input.
type Edge struct{ From, To string }

// BuildDAG converts a “package → dependents” map into an explicit, acyclic
// build graph that maximizes parallelism.
//
// - Packages in cycles appear twice: as “pkg” and “pkg#2”.
// - For edges u → v within a cyclic component:
//   - If idx(u) < idx(v), then u → v and u#2 → v#2.
//   - If idx(u) > idx(v), then u → v#2.
//     where idx(.) is the position in the component’s deterministic BFS order.
//     This breaks cycles while preserving dependency semantics.
func BuildDAG(deps map[string][]string, entry string) (nodes []string, edges []Edge) {
	nodes, edges = buildDAG(deps, entry)
	edges = reduceEdges(edges)
	return nodes, edges
}

func buildDAG(deps map[string][]string, entry string) (nodes []string, edges []Edge) {
	reachable := collectReachable(deps, entry)
	sccs, compID, _ := computeSCCs(deps, reachable)

	// ------------ Helpers for deduplication -----------------------------
	nodeID := func(pkg string, secondPass bool) string {
		if secondPass {
			return pkg + "#2"
		}
		return pkg
	}

	nodeSet := map[string]struct{}{}
	addNode := func(n string) {
		if _, exists := nodeSet[n]; !exists {
			nodeSet[n] = struct{}{}
			nodes = append(nodes, n)
		}
	}

	edgeSet := map[Edge]struct{}{}
	addEdge := func(from, to string) {
		if from == to {
			return // Skip self-loops
		}
		e := Edge{From: from, To: to}
		if _, exists := edgeSet[e]; !exists {
			edgeSet[e] = struct{}{}
			edges = append(edges, e)
		}
	}

	// ------------ Per-component metadata: cyclicity and ordering --------
	isCyclic := make([]bool, len(sccs)) // True if component requires second pass
	order := make(map[string]int)       // Node → its position in component's BFS order
	for cid, comp := range sccs {
		if needsSecondPass(comp, deps) {
			isCyclic[cid] = true
		}
		bfs := bfsOrder(comp, cid, deps, reachable, compID, entry)
		for i, n := range bfs {
			order[n] = i
		}
	}

	// ------------ Create nodes ------------------------------------------
	for pkg := range reachable {
		addNode(nodeID(pkg, false))
		if isCyclic[compID[pkg]] {
			addNode(nodeID(pkg, true))
		}
	}

	// ------------ Create edges ------------------------------------------
	for u := range reachable {
		for _, v := range deps[u] {
			if _, reachable := reachable[v]; !reachable {
				continue
			}
			cu, cv := compID[u], compID[v]

			// -------- Edges within the same component -------------------
			if cu == cv {
				// Handle explicit self-loops in cyclic components
				if u == v && isCyclic[cu] {
					addEdge(nodeID(u, false), nodeID(u, true))
					continue
				}

				// Acyclic components: preserve original edge
				if !isCyclic[cu] {
					addEdge(nodeID(u, false), nodeID(v, false))
					continue
				}

				// Cyclic components: adjust based on BFS order
				if order[u] < order[v] {
					// Forward edge: duplicate across passes
					addEdge(nodeID(u, false), nodeID(v, false))
					addEdge(nodeID(u, true), nodeID(v, true))
				} else if order[u] > order[v] {
					// Backward edge: shift to second pass of destination
					addEdge(nodeID(u, false), nodeID(v, true))
				}
				continue
			}

			// -------- Edges between different components ----------------
			from := nodeID(u, isCyclic[cu]) // Use second pass if source is cyclic
			to := nodeID(v, false)          // Always first pass for destination
			addEdge(from, to)
		}
	}

	return nodes, edges
}

// reduceEdges computes the transitive reduction of a DAG.
// It runs in approximately O(V·V/64 + E·d̄) time, where d̄ is the average out-degree.
// Assumes the input edges form a DAG; returns nil if a cycle is detected.
func reduceEdges(edges []Edge) []Edge {
	//--------------------------------------------------------------------
	// 1. Map node names to compact integer indices for efficiency.
	//--------------------------------------------------------------------
	nodeIndex := make(map[string]int, 2*len(edges))
	nodeNames := []string{}
	getIndex := func(s string) int {
		if i, exists := nodeIndex[s]; exists {
			return i
		}
		i := len(nodeNames)
		nodeIndex[s] = i
		nodeNames = append(nodeNames, s)
		return i
	}
	for _, e := range edges {
		getIndex(e.From)
		getIndex(e.To)
	}
	numNodes := len(nodeNames)       // Number of vertices
	bitWords := (numNodes + 63) / 64 // uint64 words per bit-set

	//--------------------------------------------------------------------
	// 2. Build adjacency lists and in-degrees for topological sort.
	//--------------------------------------------------------------------
	adj := make([][]int, numNodes)
	inDegree := make([]int, numNodes)
	for _, e := range edges {
		u, v := nodeIndex[e.From], nodeIndex[e.To]
		adj[u] = append(adj[u], v)
		inDegree[v]++
	}

	//--------------------------------------------------------------------
	// 3. Compute topological order using Kahn's algorithm.
	//--------------------------------------------------------------------
	topoOrder := make([]int, 0, numNodes)
	queue := list.New()
	for v, deg := range inDegree {
		if deg == 0 {
			queue.PushBack(v)
		}
	}
	for queue.Len() > 0 {
		v := queue.Remove(queue.Front()).(int)
		topoOrder = append(topoOrder, v)
		for _, w := range adj[v] {
			inDegree[w]--
			if inDegree[w] == 0 {
				queue.PushBack(w)
			}
		}
	}
	if len(topoOrder) != numNodes {
		// Cycle detected; algorithm assumes DAG. Bail out.
		return nil
	}

	//--------------------------------------------------------------------
	// 4. Compute reachability bit-sets (direct children + descendants).
	//--------------------------------------------------------------------
	reach := make([][]uint64, numNodes)
	for i := range reach {
		reach[i] = make([]uint64, bitWords)
	}

	// Process in reverse topological order (leaves first).
	for i := len(topoOrder) - 1; i >= 0; i-- {
		u := topoOrder[i]
		for _, v := range adj[u] {
			// Union descendants of v
			for w := 0; w < bitWords; w++ {
				reach[u][w] |= reach[v][w]
			}
			// Add v itself
			reach[u][v/64] |= 1 << (v & 63)
		}
	}

	//--------------------------------------------------------------------
	// 5. Filter edges: remove u→v if there's an alternative path u→w→...→v.
	//--------------------------------------------------------------------
	reducedEdges := make([]Edge, 0, len(edges))
	for _, e := range edges {
		u, v := nodeIndex[e.From], nodeIndex[e.To]
		isRedundant := false
		for _, w := range adj[u] {
			if w == v {
				continue // Ignore the edge itself
			}
			if (reach[w][v/64] >> (v & 63) & 1) == 1 {
				isRedundant = true
				break
			}
		}
		if !isRedundant {
			reducedEdges = append(reducedEdges, e)
		}
	}
	return reducedEdges
}

// ============================================================
// Internal helpers
// ============================================================

// bfsOrder computes a deterministic BFS ordering of nodes in a component.
//   - Starts from "gateway" nodes (incoming edges from outside the component),
//     or the entry node if it's in the component.
//   - Falls back to lexicographic order if no gateways.
//   - Follows the original dependency edges.
func bfsOrder(
	comp []string,
	cid int,
	deps map[string][]string,
	reachable map[string]bool,
	compID map[string]int,
	entry string,
) []string {
	compSet := make(map[string]struct{}, len(comp))
	for _, n := range comp {
		compSet[n] = struct{}{}
	}

	// 1. If entry is in this component, start BFS from it.
	if _, ok := compSet[entry]; ok {
		return bfsFrom([]string{entry}, compSet, deps)
	}

	// 2. Find gateways: nodes with incoming edges from outside the component.
	gatewaySet := map[string]struct{}{}
	for outside := range reachable {
		if compID[outside] == cid {
			continue // Same component; skip
		}
		for _, dep := range deps[outside] {
			if _, inComp := compSet[dep]; inComp {
				gatewaySet[dep] = struct{}{}
			}
		}
	}
	if len(gatewaySet) > 0 {
		gateways := keysSorted(gatewaySet)
		return bfsFrom(gateways, compSet, deps)
	}

	// 3. Fallback: all nodes in lexicographic order.
	return keysSorted(compSet)
}

// bfsFrom performs a BFS starting from given nodes, restricted to allowed set.
// Ensures deterministic order by sorting neighbors.
func bfsFrom(starts []string, allowed map[string]struct{}, deps map[string][]string) []string {
	visited := map[string]struct{}{}
	queue := append([]string(nil), starts...) // FIFO queue (nil sentinel unnecessary but kept for clarity)
	var order []string

	for len(queue) > 0 {
		cur := queue[0]
		queue = queue[1:]
		if _, seen := visited[cur]; seen {
			continue
		}
		visited[cur] = struct{}{}
		order = append(order, cur)

		// Collect unvisited neighbors within the allowed set.
		var neighbors []string
		for _, dep := range deps[cur] {
			if _, ok := allowed[dep]; ok {
				if _, seen := visited[dep]; !seen {
					neighbors = append(neighbors, dep)
				}
			}
		}
		if len(neighbors) > 0 {
			sort.Strings(neighbors) // Ensure deterministic order
			queue = append(queue, neighbors...)
		}
	}

	// Append any missed nodes (disconnected) in sorted order.
	if len(visited) < len(allowed) {
		for _, n := range keysSorted(allowed) {
			if _, seen := visited[n]; !seen {
				order = append(order, n)
			}
		}
	}
	return order
}

// keysSorted returns the keys of a set map in sorted order.
func keysSorted(set map[string]struct{}) []string {
	keys := make([]string, 0, len(set))
	for k := range set {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// collectReachable computes the set of nodes reachable from the start via DFS.
func collectReachable(deps map[string][]string, start string) map[string]bool {
	reachable := map[string]bool{}
	stack := []string{start}
	for len(stack) > 0 {
		n := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		if reachable[n] {
			continue
		}
		reachable[n] = true
		stack = append(stack, deps[n]...)
	}
	return reachable
}

// sortedKeys returns the keys of any map[string]T in sorted order.
func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ---------------- Tarjan's SCC Algorithm ----------------------------

// tarjanData holds state for Tarjan's SCC algorithm.
type tarjanData struct {
	index     int
	stack     []string
	idx, low  map[string]int // Discovery index and lowlink
	onStack   map[string]bool
	sccs      [][]string
	deps      map[string][]string
	reachable map[string]bool
}

// strongConnect is the recursive core of Tarjan's algorithm.
func (t *tarjanData) strongConnect(v string) {
	t.index++
	t.idx[v], t.low[v] = t.index, t.index
	t.stack = append(t.stack, v)
	t.onStack[v] = true

	for _, w := range t.deps[v] {
		if !t.reachable[w] {
			continue
		}
		if t.idx[w] == 0 {
			t.strongConnect(w)
			if t.low[w] < t.low[v] {
				t.low[v] = t.low[w]
			}
		} else if t.onStack[w] && t.idx[w] < t.low[v] {
			t.low[v] = t.idx[w]
		}
	}

	if t.low[v] == t.idx[v] { // v is the root of an SCC
		var comp []string
		for {
			w := t.stack[len(t.stack)-1]
			t.stack = t.stack[:len(t.stack)-1]
			t.onStack[w] = false
			comp = append(comp, w)
			if w == v {
				break
			}
		}
		// Sort component by discovery index for determinism.
		sort.Slice(comp, func(i, j int) bool { return t.idx[comp[i]] < t.idx[comp[j]] })
		t.sccs = append(t.sccs, comp)
	}
}

// computeSCCs runs Tarjan's algorithm on the reachable subgraph.
// Returns SCCs, component ID map, and discovery index map.
// Iterates over nodes in sorted order for determinism.
func computeSCCs(deps map[string][]string, reachable map[string]bool) ([][]string, map[string]int, map[string]int) {
	td := &tarjanData{
		idx:       map[string]int{},
		low:       map[string]int{},
		onStack:   map[string]bool{},
		deps:      deps,
		reachable: reachable,
	}
	for _, n := range sortedKeys(reachable) {
		if td.idx[n] == 0 {
			td.strongConnect(n)
		}
	}

	compID := make(map[string]int, len(reachable))
	for i, comp := range td.sccs {
		for _, n := range comp {
			compID[n] = i
		}
	}
	return td.sccs, compID, td.idx
}

// needsSecondPass returns true if the component is cyclic (size > 1 or self-loop).
func needsSecondPass(comp []string, deps map[string][]string) bool {
	if len(comp) > 1 {
		return true
	}
	n := comp[0]
	for _, d := range deps[n] {
		if d == n {
			return true
		}
	}
	return false
}
