package:
  name: ca-certificates
  version: 2024.2.69_v8.0.303-91.4.el9_4
  epoch: 0
  description: "ca-certificates library package"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: ""
      uri: https://example.com/source.tar.gz
      strip-components: 1

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ca-certificates-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ca-certificates
    description: ca-certificates dev

update:
  enabled: true
  release-monitor:
    identifier: 0
