package apkproxy_test

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// createMinimalAPK creates a minimal valid APK package for testing
// Returns the path to the created APK file
func createMinimalAPK() (string, error) {
	return createMinimalAPKForPackage("test-package")
}

func createMinimalAPKForPackage(packageName string) (string, error) {
	// Create temporary file for APK
	tmpFile, err := os.CreateTemp("", "test-package-*.apk")
	if err != nil {
		return "", fmt.Errorf("failed to create temp APK file: %w", err)
	}
	apkPath := tmpFile.Name()
	defer tmpFile.Close()

	// PKGINFO content
	pkgInfoContent := []byte(fmt.Sprintf(`# Generated by integration test
pkgname = %s
pkgver = 1.0.0-r0
pkgdesc = Minimal test package for APK proxy integration testing
url = https://test.securebuild.com
builddate = 1640995200
packager = SecureBuild Test <test@securebuild.com>
size = 512
arch = x86_64
origin = %s
license = MIT
`, packageName, packageName))

	// Create control.tar.gz (first gzip stream containing .PKGINFO)
	var controlBuf bytes.Buffer
	gzipWriter := gzip.NewWriter(&controlBuf)
	tarWriter := tar.NewWriter(gzipWriter)

	// Add .PKGINFO to control tar
	pkgInfoHeader := &tar.Header{
		Name: ".PKGINFO",
		Mode: 0644,
		Size: int64(len(pkgInfoContent)),
	}
	if err := tarWriter.WriteHeader(pkgInfoHeader); err != nil {
		return "", fmt.Errorf("failed to write .PKGINFO header: %w", err)
	}
	if _, err := tarWriter.Write(pkgInfoContent); err != nil {
		return "", fmt.Errorf("failed to write .PKGINFO content: %w", err)
	}

	if err := tarWriter.Close(); err != nil {
		return "", fmt.Errorf("failed to close tar writer: %w", err)
	}
	if err := gzipWriter.Close(); err != nil {
		return "", fmt.Errorf("failed to close gzip writer: %w", err)
	}

	// Create data.tar.gz (second gzip stream containing actual files)
	var dataBuf bytes.Buffer
	dataGzipWriter := gzip.NewWriter(&dataBuf)
	dataTarWriter := tar.NewWriter(dataGzipWriter)

	// Add a simple test file to data tar
	testFileContent := []byte("hello world from test package\n")
	testFileHeader := &tar.Header{
		Name: "usr/share/test/hello.txt",
		Mode: 0644,
		Size: int64(len(testFileContent)),
	}
	if err := dataTarWriter.WriteHeader(testFileHeader); err != nil {
		return "", fmt.Errorf("failed to write test file header: %w", err)
	}
	if _, err := dataTarWriter.Write(testFileContent); err != nil {
		return "", fmt.Errorf("failed to write test file content: %w", err)
	}

	if err := dataTarWriter.Close(); err != nil {
		return "", fmt.Errorf("failed to close data tar writer: %w", err)
	}
	if err := dataGzipWriter.Close(); err != nil {
		return "", fmt.Errorf("failed to close data gzip writer: %w", err)
	}

	// Write both gzip streams to APK file
	// APK format: control.tar.gz + data.tar.gz
	if _, err := io.Copy(tmpFile, &controlBuf); err != nil {
		return "", fmt.Errorf("failed to write control stream to APK: %w", err)
	}
	if _, err := io.Copy(tmpFile, &dataBuf); err != nil {
		return "", fmt.Errorf("failed to write data stream to APK: %w", err)
	}

	return apkPath, nil
}

// findProjectRoot walks up from current directory to find go.mod
func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for dir != "/" {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		dir = filepath.Dir(dir)
	}

	return "", fmt.Errorf("could not find project root (go.mod)")
}
