database: securebuild
name: package
seedData:
  rows:
    - columns:
        - column: id
          value:
            str: "test-package-release-id-123"
        - column: name
          value:
            str: "test-package-release"
        - column: created_at
          value:
            str: "2024-01-01T00:00:00Z"
        - column: updated_at
          value:
            str: "2024-01-01T00:00:00Z"
