database: securebuild
name: dynamic_config
schema:
  postgres:
    primaryKey:
    - key
    columns:
    - name: key
      type: text
      constraints:
        notNull: true
    - name: value
      type: text
      constraints:
        notNull: true