package cli

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"
	"time"

	"github.com/google/go-containerregistry/pkg/name"
	v1 "github.com/google/go-containerregistry/pkg/v1"
	"github.com/google/go-containerregistry/pkg/v1/layout"
	"github.com/google/go-containerregistry/pkg/v1/tarball"
	"github.com/securebuildhq/securebuild/pkg/logger"
	"gopkg.in/yaml.v3"
)

// ImageTestDefinition represents the test configuration from .test.yaml files
type ImageTestDefinition struct {
	ReferenceImage string          `yaml:"referenceImage,omitempty"`
	Test           ImageTestConfig `yaml:"test"`
}

// ImageTestConfig represents the test configuration section with a pipeline
type ImageTestConfig struct {
	Pipeline []ImageTestStep `yaml:"pipeline"`
}

// ImageTestStep represents a single step in the test pipeline
// Either Uses (for reusable pipeline) or Runs (for custom script) must be set
// If Name is not provided and Uses is set, the pipeline path will be used as the name
type ImageTestStep struct {
	// Optional name, defaults to pipeline path if Uses is set
	Name string `yaml:"name,omitempty"`
	// Reference to reusable pipeline
	Uses string `yaml:"uses,omitempty"`
	// Input parameters for reusable pipeline
	With map[string]string `yaml:"with,omitempty"`
	// Inline custom script
	Runs string `yaml:"runs,omitempty"`
	// Environment variable overrides for this step
	Environment map[string]string `yaml:"environment,omitempty"`
}

// PipelineInput represents an input parameter definition for a reusable pipeline
type PipelineInput struct {
	// Human-readable description of the input
	Description string `yaml:"description,omitempty"`
	// Default value if not provided via 'with:'
	Default string `yaml:"default,omitempty"`
	// Whether this input must be provided
	Required bool `yaml:"required,omitempty"`
}

// PipelineDefinition represents a complete pipeline configuration with inputs
type PipelineDefinition struct {
	// Name of the pipeline
	Name string `yaml:"name"`
	// Input parameter definitions
	Inputs map[string]PipelineInput `yaml:"inputs,omitempty"`
	// Steps to execute
	Pipeline []ImageTestStep `yaml:"pipeline"`
}

// loadImageTestDefinition loads and parses a .test.yaml file
// Returns os.IsNotExist error if file doesn't exist (caller handles gracefully)
func loadImageTestDefinition(testFilePath string) (*ImageTestDefinition, error) {
	// Read file (will return os.IsNotExist if file doesn't exist)
	data, err := os.ReadFile(testFilePath)
	if err != nil {
		return nil, err
	}

	// Parse YAML
	var testDef ImageTestDefinition
	if err := yaml.Unmarshal(data, &testDef); err != nil {
		return nil, fmt.Errorf("failed to parse test file: %w", err)
	}

	return &testDef, nil
}

// parseImageTestPipeline parses an image test pipeline YAML file
// Note: Input name validation is performed by the API layer before pipelines are saved
func parseImageTestPipeline(yamlContent []byte) (*PipelineDefinition, error) {
	var pipeline PipelineDefinition
	if err := yaml.Unmarshal(yamlContent, &pipeline); err != nil {
		return nil, fmt.Errorf("failed to parse image test pipeline: %w", err)
	}
	return &pipeline, nil
}

// executeImageTest executes all tests for an image across all available architectures
func executeImageTest(ctx context.Context, config *ImageBuildConfig, testDef *ImageTestDefinition) error {
	logger.Info("Starting image test execution")

	// Determine reference image: use testDef.ReferenceImage if provided,
	// otherwise fall back to AlternateImageRef
	referenceImage := config.AlternateImageRef
	if testDef.ReferenceImage != "" {
		referenceImage = testDef.ReferenceImage
	}
	if referenceImage == "" {
		return fmt.Errorf("test definition missing referenceImage and no alternate image configured")
	}

	// Create image.tar for Docker from the OCI layout generated by apko build
	logger.Info("Creating image.tar for Docker from OCI layout")
	if err := createAndLoadImageTarFromOCILayout(ctx, config.WorkDir); err != nil {
		return fmt.Errorf("failed to create image.tar for Docker from OCI layout: %w", err)
	}

	// Test the architecture of the builder host we've landed on.
	// TODO: Add support for testing other architectures, for now we execute
	// the test for the architecture of the builder host we've landed on.
	logger.Infof("Running image tests for architecture: %s", runtime.GOARCH)

	if err := executeImageTestForArchitecture(ctx, config, testDef, referenceImage, runtime.GOARCH); err != nil {
		return fmt.Errorf("image tests failed for architecture %s: %w", runtime.GOARCH, err)
	}

	logger.Infof("Image tests passed for architecture: %s", runtime.GOARCH)

	return nil
}

// createAndLoadImageTarFromOCILayout creates an image.tar file from OCI layout
// for Docker and loads it into Docker.
func createAndLoadImageTarFromOCILayout(ctx context.Context, workDir string) error {
	// Load the OCI layout
	layoutPath := layout.Path(workDir)
	imageIndex, err := layoutPath.ImageIndex()
	if err != nil {
		return fmt.Errorf("failed to load OCI layout: %w", err)
	}

	// Get the index manifest
	indexManifest, err := imageIndex.IndexManifest()
	if err != nil {
		return fmt.Errorf("failed to get index manifest: %w", err)
	}

	// Build a map of tags to images for both architectures
	tagToImage := make(map[name.Tag]v1.Image)

	for _, desc := range indexManifest.Manifests {
		if desc.Platform == nil {
			continue
		}

		// Get the image for this platform
		img, err := imageIndex.Image(desc.Digest)
		if err != nil {
			return fmt.Errorf("failed to get image for platform %s/%s: %w",
				desc.Platform.OS, desc.Platform.Architecture, err)
		}

		// Create a tag with architecture suffix matching what Docker expects
		var tagStr string
		switch desc.Platform.Architecture {
		case "amd64":
			tagStr = "image:latest-amd64"
		case "arm64":
			tagStr = "image:latest-arm64"
		default:
			continue
		}

		tag, err := name.NewTag(tagStr)
		if err != nil {
			return fmt.Errorf("failed to create tag %s: %w", tagStr, err)
		}

		tagToImage[tag] = img
	}

	// Write the multi-image tarball
	tarballPath := filepath.Join(workDir, "image.tar")
	if err := tarball.MultiWriteToFile(tarballPath, tagToImage); err != nil {
		return fmt.Errorf("failed to write tarball: %w", err)
	}

	logger.Debugf("Created image.tar for Docker at: %s", tarballPath)

	// Load the multi-arch image tarball into Docker
	logger.Debugf("Loading built image tarball into Docker: %s", tarballPath)
	loadCmd := exec.CommandContext(ctx, "docker", "load", "-i", tarballPath)
	loadOutput, err := loadCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to load image: %w, output: %s", err, loadOutput)
	}

	return nil
}

// executeImageTestForArchitecture executes all tests for a specific architecture.
func executeImageTestForArchitecture(ctx context.Context, config *ImageBuildConfig, testDef *ImageTestDefinition, referenceImage, arch string) error {
	// Construct the image name from config
	// The loaded image has architecture-specific tags like "image:latest-amd64" and "image:latest-arm64"
	if len(config.Tags) == 0 {
		return fmt.Errorf("no tags provided in build config")
	}

	dockerPlatform := "linux/" + arch

	// Docker load creates images with simple tags (e.g., "image:latest-amd64")
	// These match the tags created by createAndLoadImageTarFromOCILayout
	ourImageName := fmt.Sprintf("image:latest-%s", arch)
	logger.Infof("Testing ourImage: %s", ourImageName)

	const maxPullRetries = 3
	basePullDelay := 5 * time.Second
	var lastPullErr error

	for attempt := 0; attempt < maxPullRetries; attempt++ {
		logger.Infof("Pulling refImage: %s (platform: %s, attempt %d/%d)",
			referenceImage, dockerPlatform, attempt+1, maxPullRetries)

		pullCmd := exec.CommandContext(ctx, "docker", "pull", "--platform", dockerPlatform, referenceImage)
		pullOutput, err := pullCmd.CombinedOutput()

		if err == nil {
			logger.Info("Reference image pulled successfully")
			break
		}

		lastPullErr = fmt.Errorf("attempt %d failed to pull reference image: %w, output: %s",
			attempt+1, err, pullOutput)

		if attempt < maxPullRetries-1 {
			delay := basePullDelay * time.Duration(1<<attempt)
			logger.Warnf("Failed to pull reference image, retrying in %v: %v", delay, err)
			time.Sleep(delay)
			continue
		}

		return fmt.Errorf("failed to pull reference image after %d attempts: %w", maxPullRetries, lastPullErr)
	}

	// Execute each step in the test pipeline
	for i, step := range testDef.Test.Pipeline {
		if err := executeImageTestPipeline(ctx, &ImageTestConfig{Pipeline: []ImageTestStep{step}}, ourImageName, referenceImage, arch, i+1); err != nil {
			// If no step name is provided, use the uses pipeline path as step
			// name as a best effort.
			stepName := step.Name
			if stepName == "" && step.Uses != "" {
				stepName = step.Uses
			}
			return fmt.Errorf("test step %s failed: %w", stepName, err)
		}
	}

	logger.Info("All image tests passed")
	return nil
}

// executeImageTestPipeline executes an image test pipeline
// System variables (ourImage, refImage, arch) are provided to template context, not as environment variables
func executeImageTestPipeline(ctx context.Context, testConfig *ImageTestConfig, ourImage, refImage, arch string, stepNumber int) error {
	// Start with base system environment
	cmdEnv := os.Environ()

	// Execute each top-level pipeline step
	// Top-level steps start with empty inputs; when they use reusable pipelines with 'uses:' and 'with:',
	// inputs are resolved from the pipeline's input definitions and the provided 'with:' values
	emptyInputs := make(map[string]string)
	for _, step := range testConfig.Pipeline {
		if err := executePipelineStep(ctx, step, cmdEnv, emptyInputs, ourImage, refImage, arch, stepNumber); err != nil {
			return err
		}
	}

	return nil
}

// validatePipelinePath validates a pipeline path to prevent path traversal attacks
// Allows only alphanumeric characters, underscores, hyphens, and forward slashes
// Rejects paths with: .., ., leading/trailing slashes, or empty segments
func validatePipelinePath(path string) error {
	if path == "" {
		return fmt.Errorf("pipeline path cannot be empty")
	}

	// Reject absolute paths
	if filepath.IsAbs(path) {
		return fmt.Errorf("invalid pipeline path: must be relative")
	}

	// Reject paths starting or ending with slash
	if strings.HasPrefix(path, "/") || strings.HasSuffix(path, "/") {
		return fmt.Errorf("invalid pipeline path: cannot start or end with slash")
	}

	// Validate characters: only allow alphanumeric, underscore, hyphen, and forward slash
	for _, char := range path {
		if !((char >= 'a' && char <= 'z') ||
			(char >= 'A' && char <= 'Z') ||
			(char >= '0' && char <= '9') ||
			char == '_' || char == '-' || char == '/') {
			return fmt.Errorf("invalid pipeline path: contains disallowed character: %c", char)
		}
	}

	// Split by / and validate each segment
	segments := strings.Split(path, "/")
	for _, segment := range segments {
		if segment == "" {
			return fmt.Errorf("invalid pipeline path: contains empty segment")
		}
		if segment == "." || segment == ".." {
			return fmt.Errorf("invalid pipeline path: contains . or .. segment")
		}
	}

	// Final safety check: ensure filepath.Clean doesn't change the path
	// This catches any remaining path traversal attempts
	if filepath.Clean(path) != path {
		return fmt.Errorf("invalid pipeline path: contains path traversal sequences")
	}

	return nil
}

// TemplateContext holds all variables available in pipeline script templates
type TemplateContext struct {
	// User-defined pipeline inputs (${{inputs.name}})
	Inputs map[string]string
	// The image being tested (${{ourImage}})
	OurImage string
	// The reference image to compare against (${{refImage}})
	RefImage string
	// The architecture being tested (${{arch}})
	Arch string
}

// resolveInputs merges provided inputs with pipeline input defaults, validates required inputs,
// and optionally performs template substitution on a script.
// Values from 'with:' take precedence over defaults.
// If script is provided, performs template substitution using resolved inputs and system variables.
// Returns resolved inputs map and optionally the substituted script.
// Available template variables:
//   - ${{ourImage}}: The image being tested
//   - ${{refImage}}: The reference image to compare against
//   - ${{arch}}: Current architecture being tested
//   - ${{inputs.name}}: User-defined pipeline inputs
func resolveInputs(pipelineInputs map[string]PipelineInput, providedInputs map[string]string, script string, ourImage, refImage, arch string) (map[string]string, string, error) {
	// Resolve input values
	result := make(map[string]string)

	// If pipelineInputs is nil, we're in an inline script using parent's resolved inputs
	// Copy all provided inputs directly without validation
	if pipelineInputs == nil {
		for k, v := range providedInputs {
			result[k] = v
		}
	} else {
		// Validate and merge inputs with pipeline definitions
		var missingRequired []string

		for inputName, inputDef := range pipelineInputs {
			// Use provided value if available
			if value, ok := providedInputs[inputName]; ok {
				result[inputName] = value
			} else if inputDef.Default != "" {
				// Use default if available
				result[inputName] = inputDef.Default
			} else if inputDef.Required {
				// Required input is missing and has no default
				missingRequired = append(missingRequired, inputName)
			}
		}

		if len(missingRequired) > 0 {
			return nil, "", fmt.Errorf("missing required input(s): %v", missingRequired)
		}
	}

	// If no script provided, return just the resolved inputs
	if script == "" {
		return result, "", nil
	}

	// Perform template substitution
	ctx := TemplateContext{
		Inputs:   result,
		OurImage: ourImage,
		RefImage: refImage,
		Arch:     arch,
	}

	// Add custom functions for convenient access
	funcMap := template.FuncMap{
		"inputs":   func() map[string]string { return result },
		"ourImage": func() string { return ourImage },
		"refImage": func() string { return refImage },
		"arch":     func() string { return arch },
	}

	// Parse the script as a template with ${{...}} delimiters and custom functions
	tmpl, err := template.New("script").Delims("${{", "}}").Funcs(funcMap).Parse(script)
	if err != nil {
		return nil, "", fmt.Errorf("failed to parse script template: %w", err)
	}

	// Execute the template
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return nil, "", fmt.Errorf("failed to execute script template: %w", err)
	}

	return result, buf.String(), nil
}

// executePipelineStep executes a single pipeline step with proper resource management
// inputs contains the resolved input values that will be substituted in scripts
// ourImage, refImage, and arch are system variables available to all templates
func executePipelineStep(ctx context.Context, step ImageTestStep, cmdEnv []string, inputs map[string]string, ourImage, refImage, arch string, stepNumber int) error {
	// Validate that exactly one of Uses or Runs is set
	if (step.Uses == "" && step.Runs == "") || (step.Uses != "" && step.Runs != "") {
		stepName := step.Name
		if stepName == "" {
			stepName = "<unnamed>"
		}
		return fmt.Errorf("step %s must have exactly one of 'uses' or 'runs' set", stepName)
	}

	// Determine the step name: use provided name, or default to pipeline path
	// for 'uses' if none is provided.
	stepName := step.Name
	if stepName == "" && step.Uses != "" {
		stepName = step.Uses
	}

	logger.Infof("Executing test pipeline step %d: %s", stepNumber, stepName)

	// Merge step-level environment variables with parent environment
	stepEnv := cmdEnv
	if len(step.Environment) > 0 {
		stepEnv = make([]string, len(cmdEnv))
		copy(stepEnv, cmdEnv)
		for key, value := range step.Environment {
			stepEnv = append(stepEnv, fmt.Sprintf("%s=%s", key, value))
			logger.Debugf("Setting step environment variable: %s=%s", key, value)
		}
	}

	if step.Uses != "" {
		// Validate pipeline path to prevent path traversal attacks
		if err := validatePipelinePath(step.Uses); err != nil {
			return fmt.Errorf("invalid pipeline reference in 'uses': %w", err)
		}

		// Load and execute reusable pipeline
		pipelinePath := filepath.Join("/home/builder/pipelines/images", step.Uses+".yaml")
		pipelineYAML, err := os.ReadFile(pipelinePath)
		if err != nil {
			return fmt.Errorf("failed to load image test pipeline %s: %w", step.Uses, err)
		}

		pipelineDef, err := parseImageTestPipeline(pipelineYAML)
		if err != nil {
			return fmt.Errorf("failed to parse image test pipeline %s: %w", step.Uses, err)
		}

		// Resolve inputs: merge 'with:' values with pipeline's input definitions and defaults
		// Validates that all required inputs are provided
		// No script substitution needed here (empty string), just resolve inputs
		resolvedInputs, _, err := resolveInputs(pipelineDef.Inputs, step.With, "", ourImage, refImage, arch)
		if err != nil {
			return fmt.Errorf("failed to resolve inputs for pipeline %s: %w", step.Uses, err)
		}

		logger.Debugf("Resolved inputs for pipeline %s: %v", step.Uses, resolvedInputs)

		// Recursively execute all steps in the loaded pipeline with resolved inputs
		// Pass the step's environment (which may have overrides) to nested steps
		for _, nestedStep := range pipelineDef.Pipeline {
			if err := executePipelineStep(ctx, nestedStep, stepEnv, resolvedInputs, ourImage, refImage, arch, stepNumber); err != nil {
				return err
			}
		}
	} else {
		// Execute inline script with input substitution using Go templates
		// Pass empty pipelineInputs map since inline scripts use the parent's resolved inputs
		_, script, err := resolveInputs(nil, inputs, step.Runs, ourImage, refImage, arch)
		if err != nil {
			return fmt.Errorf("failed to substitute inputs in script: %w", err)
		}

		logger.Debugf("Executing script after input substitution: %s", script)

		cmd := exec.CommandContext(ctx, "bash", "-c", script)
		cmd.Env = stepEnv // Use step environment (includes any overrides)

		output, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("test pipeline step %d (%s) failed: %w, output: %s", stepNumber, stepName, err, output)
		}
	}

	logger.Infof("Test pipeline step %d passed: %s", stepNumber, stepName)
	return nil
}
