// Keyless signing & attestation helpers.
//
// This code path is invoked **only** by the VM-based build pipeline via
// pkg/listener/update-build-image-status.go.  The legacy local-builder path
// continues to use the key-based helpers in cosign-api.go.
//
// Failures in Fulcio or Rekor are surfaced as errors to the caller but do not
// abort the overall image build; the listener logs a warning and continues so
// that a transient Sigstore outage does not break the build pipeline.

package cosign

import (
	"bytes"
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/asn1"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"math/big"
	"net/url"
	"os"
	"strings"
	"sync"

	// internal packages
	"github.com/securebuildhq/securebuild/pkg/logger"
	oci "github.com/securebuildhq/securebuild/pkg/oci"
	"github.com/securebuildhq/securebuild/pkg/oidc"
	"github.com/securebuildhq/securebuild/pkg/param"
	"github.com/securebuildhq/securebuild/pkg/registry"

	// third-party
	cosign "github.com/sigstore/cosign/v2/pkg/cosign"
	cosignbundle "github.com/sigstore/cosign/v2/pkg/cosign/bundle"
	fulcioclient "github.com/sigstore/fulcio/pkg/api"
	rekorclient "github.com/sigstore/rekor/pkg/client"
	generatedclient "github.com/sigstore/rekor/pkg/generated/client"
	sigpayload "github.com/sigstore/sigstore/pkg/signature/payload"

	"go.uber.org/zap"
)

// -----------------------------------------------------------------------------
// Indirection points (function variables) for external side-effects.
// In production these point to the real implementations, but unit tests can
// replace them with mocks by re-assigning the package-level vars.
// -----------------------------------------------------------------------------

// Fulcio
type fulcioSigningClient interface {
	SigningCert(fulcioclient.CertificateRequest, string) (*fulcioclient.CertificateResponse, error)
}

var (
	fulcioClientOnce   sync.Once
	sharedFulcioClient fulcioSigningClient
	// newFulcioClient lazily initialises and returns a singleton Fulcio client
	newFulcioClient = func(u *url.URL) fulcioSigningClient {
		fulcioClientOnce.Do(func() {
			sharedFulcioClient = fulcioclient.NewClient(u)
		})
		return sharedFulcioClient
	}
)

// Rekor
var (
	rekorClientMu      sync.Mutex
	cachedRekorClients = make(map[string]*generatedclient.Rekor)
	// getRekorClient returns a cached Rekor client per base URL, creating it
	// on first use. This avoids leaking sockets by reusing the underlying
	// http.Client across invocations.
	getRekorClient = func(baseURL string) (*generatedclient.Rekor, error) {
		rekorClientMu.Lock()
		defer rekorClientMu.Unlock()
		if c, ok := cachedRekorClients[baseURL]; ok {
			return c, nil
		}
		c, err := rekorclient.GetRekorClient(baseURL)
		if err != nil {
			return nil, err
		}
		cachedRekorClients[baseURL] = c
		return c, nil
	}
)

// TLog upload helper functions from cosign
var tlogUpload = cosign.TLogUpload

// For attestations we need a DSSE entry so that the verification code can
// extract the signature from the bundle (intoto_v002 is not yet generated by
// the upstream helper). Use the DSSE envelope uploader.
var tlogUploadDSSE = cosign.TLogUploadDSSEEnvelope

// OCI DB helpers
var storeArtifactBlob = oci.StoreArtifactBlob
var getArtifactBlobByDigest = oci.GetArtifactBlobByDigest
var newOCIArtifactManifest = oci.NewOCIArtifactManifest
var storeFullArtifactManifest = oci.StoreFullArtifactManifest

// CosignSignKeylessWithCustomSubject performs keyless signing of an image using an
// ephemeral ECDSA key and a custom subject. The signature payload follows the
// Simple Signing spec used by cosign. The resulting payload blob and an OCI
// artifact manifest are stored in the local DB, similar to
// CosignAttestWithCustomSubject.
//
// NOTE: A Sigstore OIDC ID token is fetched for future integration with
// Fulcio/Rekor, but the current implementation performs a local signature only.
func CosignSignKeylessWithCustomSubject(ctx context.Context, imageRef string, oidcProvider oidc.OIDCProvider, imageCatalogID string) error {
	// ---------------------------------------------------------------------
	// 1. Obtain the OIDC ID token (future-proof; not yet used downstream)
	// ---------------------------------------------------------------------
	// Obtain the OIDC ID token that proves our workload identity. This will be
	// passed to Fulcio in order to get a short-lived X.509 signing certificate.
	idToken, err := oidcProvider.GetIDToken(ctx, oidc.OIDCAudienceDefault)
	if err != nil {
		return fmt.Errorf("failed to obtain OIDC ID token for keyless signing: %w", err)
	}

	// ---------------------------------------------------------------------
	// 2. Build the Simple Signing payload with a custom subject
	// ---------------------------------------------------------------------
	// Extract the digest (sha256:abc123) portion from imageRef
	digest := imageRef
	if idx := strings.LastIndex(imageRef, "@"); idx != -1 {
		digest = imageRef[idx+1:]
	}
	digest = strings.TrimPrefix(digest, "sha256:")

	// Final subject name using the OCI prefix (falls back to registry prefix)
	ociPrefix := registry.NormalizePrefix(param.GetParam(ctx).OCIImagePrefix)
	if ociPrefix == "" {
		ociPrefix = registry.NormalizePrefix(param.GetParam(ctx).RegistryImagePrefix)
	}
	finalSubjectName := ociPrefix

	// Build canonical Simple Signing payload using official cosign struct
	var scPayload sigpayload.SimpleContainerImage
	scPayload.Critical.Type = "cosign container image signature"
	scPayload.Critical.Image.DockerManifestDigest = "sha256:" + digest
	scPayload.Critical.Identity.DockerReference = finalSubjectName

	payloadBytes, err := json.Marshal(scPayload)
	if err != nil {
		return fmt.Errorf("failed to marshal simple signing payload: %w", err)
	}

	// ---------------------------------------------------------------------
	// 3. Sign the payload with an ephemeral ECDSA key (P-256)
	// ---------------------------------------------------------------------
	privKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("failed to generate ephemeral ECDSA key: %w", err)
	}

	// ---------------------------------------------------------------------
	// 3a. Obtain a short-lived X.509 signing certificate from Fulcio
	// ---------------------------------------------------------------------
	fulcioURL := "https://fulcio.sigstore.dev" // TODO(config): param/env

	// Fulcio client helper from github.com/sigstore/fulcio/pkg/api
	u, err := url.Parse(fulcioURL)
	if err != nil {
		return fmt.Errorf("invalid fulcio URL %q: %w", fulcioURL, err)
	}

	fClient := newFulcioClient(u)

	// ------------------------------------------------------------------
	// Prepare the certificate request: PEM public key + signed email proof
	// ------------------------------------------------------------------

	// Marshal public key to PEM (Fulcio expects PEM for the Key content)
	pubKeyDER, err := x509.MarshalPKIXPublicKey(&privKey.PublicKey)
	if err != nil {
		return fmt.Errorf("failed to marshal public key: %w", err)
	}
	pubKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubKeyDER})

	// Extract email (or sub) from the OIDC token to sign as proof-of-possession
	var emailToSign string
	{
		parts := strings.Split(idToken, ".")
		if len(parts) < 2 {
			return fmt.Errorf("invalid id token format")
		}
		payloadRaw, err := base64.RawURLEncoding.DecodeString(parts[1])
		if err != nil {
			return fmt.Errorf("failed to decode id token payload: %w", err)
		}
		var claims map[string]interface{}
		if err := json.Unmarshal(payloadRaw, &claims); err != nil {
			return fmt.Errorf("failed to unmarshal id token claims: %w", err)
		}
		if v, ok := claims["email"].(string); ok {
			emailToSign = v
		} else if v, ok := claims["sub"].(string); ok {
			emailToSign = v
		} else {
			return fmt.Errorf("id token missing email or sub claim")
		}
	}

	// Sign email using the private key as proof
	emailHash := sha256.Sum256([]byte(emailToSign))
	rP, sP, err := ecdsa.Sign(rand.Reader, privKey, emailHash[:])
	if err != nil {
		return fmt.Errorf("failed to sign email proof: %w", err)
	}
	sigProof, err := asn1.Marshal(struct{ R, S *big.Int }{rP, sP})
	if err != nil {
		return fmt.Errorf("failed to marshal email proof signature: %w", err)
	}

	certReq := fulcioclient.CertificateRequest{
		PublicKey: fulcioclient.Key{
			Content:   pubKeyPEM,
			Algorithm: "ecdsa",
		},
		SignedEmailAddress: sigProof,
	}

	certResp, err := fClient.SigningCert(certReq, idToken)
	if err != nil {
		return fmt.Errorf("failed to obtain signing certificate from fulcio: %w", err)
	}

	certPEM := certResp.CertPEM

	// ---------------------------------------------------------------------
	// 3b. Sign the payload (ECDSA P-256) to obtain signature bytes
	// ---------------------------------------------------------------------

	hash := sha256.Sum256(payloadBytes)
	rSig, sSig, err := ecdsa.Sign(rand.Reader, privKey, hash[:])
	if err != nil {
		return fmt.Errorf("failed to sign payload: %w", err)
	}
	sigStruct := struct{ R, S *big.Int }{rSig, sSig}
	sigBytes, err := asn1.Marshal(sigStruct)
	if err != nil {
		return fmt.Errorf("failed to marshal ECDSA signature: %w", err)
	}

	signatureBase64 := base64.StdEncoding.EncodeToString(sigBytes)

	// ---------------------------------------------------------------------
	// 3c. Upload the signature + cert to the Rekor transparency log
	// ---------------------------------------------------------------------

	payloadHash := sha256.New()
	payloadHash.Write(payloadBytes)

	rekorURL := "https://rekor.sigstore.dev" // TODO(config): param/env
	rClient, err := getRekorClient(rekorURL)
	if err != nil {
		return fmt.Errorf("failed to create rekor client: %w", err)
	}

	logEntry, err := tlogUpload(ctx, rClient, sigBytes, payloadHash, certPEM)
	if err != nil {
		return fmt.Errorf("failed to upload signature to Rekor: %w", err)
	}

	bundleObj := cosignbundle.EntryToBundle(logEntry)
	bundleJSON, err := json.Marshal(bundleObj)
	if err != nil {
		return fmt.Errorf("failed to marshal Rekor bundle: %w", err)
	}

	// ---------------------------------------------------------------------
	// 4. Store the payload blob in the DB (after successful tlog upload)
	// ---------------------------------------------------------------------

	payloadHashHex := fmt.Sprintf("sha256:%x", sha256.Sum256(payloadBytes))
	if err := storeArtifactBlob(ctx, payloadHashHex, "application/vnd.dev.cosign.simplesigning.v1+json", payloadBytes); err != nil {
		return fmt.Errorf("failed to store signature payload blob: %w", err)
	}

	stored, _, err := getArtifactBlobByDigest(ctx, payloadHashHex)
	if err != nil {
		return fmt.Errorf("failed to fetch stored payload blob: %w", err)
	} else if !bytes.Equal(stored, payloadBytes) {
		return fmt.Errorf("payload blob mismatch after store/fetch round-trip")
	}

	// ---------------------------------------------------------------------
	// 5. Build and store the OCI artifact manifest
	// ---------------------------------------------------------------------
	subjectDigest := "sha256:" + digest
	subjectBytes, _, err := getArtifactBlobByDigest(ctx, subjectDigest)
	if err != nil {
		return fmt.Errorf("failed to fetch subject manifest for size: %w", err)
	}
	subjectDesc := oci.Descriptor{
		MediaType: "application/vnd.oci.image.manifest.v1+json",
		Digest:    subjectDigest,
		Size:      int64(len(subjectBytes)),
	}

	layerDesc := oci.Descriptor{
		MediaType: "application/vnd.dev.cosign.simplesigning.v1+json",
		Digest:    payloadHashHex,
		Size:      int64(len(payloadBytes)),
		Annotations: map[string]string{
			"dev.cosignproject.cosign/signature": signatureBase64,
			"dev.cosignproject.cosign/keyless":   "true",
			"dev.sigstore.cosign/certificate":    string(certPEM),
			"dev.sigstore.cosign/bundle":         string(bundleJSON),
		},
	}

	manifestAnnotations := map[string]string{
		"dev.cosignproject.cosign/keyless": "true",
	}

	manifestBytes, err := newOCIArtifactManifest(&subjectDesc, "application/vnd.dev.cosign.simplesigning.v1+json", []oci.Descriptor{layerDesc}, manifestAnnotations)
	if err != nil {
		return fmt.Errorf("failed to build OCI artifact manifest: %w", err)
	}

	if err := storeFullArtifactManifest(ctx, manifestBytes, imageCatalogID, nil); err != nil {
		return fmt.Errorf("failed to store signature artifact manifest: %w", err)
	}

	logger.Info("uploaded custom keyless signature to local DB (OCI-compliant)",
		zap.String("subjectDigest", digest),
		zap.Int("manifestLength", len(manifestBytes)))

	return nil
}

// -----------------------------------------------------------------------------
// CosignAttestKeylessWithCustomSubject performs keyless attestation (DSSE-wrapped
// in-toto statement) for an image digest using Fulcio + Rekor. The resulting
// DSSE envelope and an OCI artifact manifest are stored in the local DB.  The
// logic mirrors CosignAttestWithCustomSubject but replaces the private-key flow
// with the keyless flow used in CosignSignKeylessWithCustomSubject.
// -----------------------------------------------------------------------------
func CosignAttestKeylessWithCustomSubject(
	ctx context.Context,
	predicatePath string, // path to SBOM / provenance JSON file
	predicateType string, // in-toto predicateType URI
	digestRef string, // image reference with digest (…@sha256:…)
	oidcProvider oidc.OIDCProvider,
	imageCatalogID string,
) error {
	// -------------------------------------------------------------
	// 0. Load predicate bytes and unmarshal for statement building
	// -------------------------------------------------------------
	predicateBytes, err := os.ReadFile(predicatePath)
	if err != nil {
		return fmt.Errorf("failed to read predicate file: %w", err)
	}
	var predicate interface{}
	if err := json.Unmarshal(predicateBytes, &predicate); err != nil {
		return fmt.Errorf("failed to parse predicate JSON: %w", err)
	}

	// Extract digest portion (strip registry/repo@sha256:)
	digest := digestRef
	if idx := strings.LastIndex(digestRef, "@"); idx != -1 {
		digest = digestRef[idx+1:]
	}
	digest = strings.TrimPrefix(digest, "sha256:")

	// Build in-toto statement with custom subject
	statement := buildCustomSubjectStatement(ctx, digest, predicateType, predicate)
	stmtBytes, err := json.Marshal(statement)
	if err != nil {
		return fmt.Errorf("failed to marshal in-toto statement: %w", err)
	}

	// -------------------------------------------------------------
	// 1. OIDC ID token + ephemeral ECDSA key + Fulcio certificate
	// -------------------------------------------------------------
	idToken, err := oidcProvider.GetIDToken(ctx, oidc.OIDCAudienceDefault)
	if err != nil {
		return fmt.Errorf("failed to obtain OIDC ID token: %w", err)
	}

	privKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("failed to generate ephemeral key: %w", err)
	}

	// Fulcio cert request (reuse helper code from sign function)
	fulcioURL := "https://fulcio.sigstore.dev"
	u, err := url.Parse(fulcioURL)
	if err != nil {
		return fmt.Errorf("invalid fulcio URL %q: %w", fulcioURL, err)
	}
	fClient := newFulcioClient(u)

	// Prepare PEM public key + signed email proof
	pubKeyDER, _ := x509.MarshalPKIXPublicKey(&privKey.PublicKey)
	pubKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubKeyDER})

	var emailToSign string
	{
		parts := strings.Split(idToken, ".")
		if len(parts) < 2 {
			return fmt.Errorf("invalid id token format")
		}
		payloadRaw, _ := base64.RawURLEncoding.DecodeString(parts[1])
		var claims map[string]interface{}
		_ = json.Unmarshal(payloadRaw, &claims)
		if v, ok := claims["email"].(string); ok {
			emailToSign = v
		} else if v, ok := claims["sub"].(string); ok {
			emailToSign = v
		} else {
			return fmt.Errorf("id token missing email or sub claim")
		}
	}
	emailHash := sha256.Sum256([]byte(emailToSign))
	rP, sP, _ := ecdsa.Sign(rand.Reader, privKey, emailHash[:])
	sigProof, _ := asn1.Marshal(struct{ R, S *big.Int }{rP, sP})

	certResp, err := fClient.SigningCert(fulcioclient.CertificateRequest{
		PublicKey:          fulcioclient.Key{Content: pubKeyPEM, Algorithm: "ecdsa"},
		SignedEmailAddress: sigProof,
	}, idToken)
	if err != nil {
		return fmt.Errorf("failed to obtain signing certificate from fulcio: %w", err)
	}
	certPEM := certResp.CertPEM

	// -------------------------------------------------------------
	// 2. Sign the in-toto statement using DSSE Pre-Authentication Encoding
	//    ("DSSEv1 <len(pt)> <pt> <len(payload)> <payload>") so that
	//    `cosign verify-attestation` can validate it.
	// -------------------------------------------------------------

	// Helper to build PAE bytes (avoids importing the full dsse package)
	buildPAE := func(payloadType string, payload []byte) []byte {
		return []byte(fmt.Sprintf("DSSEv1 %d %s %d %s", len(payloadType), payloadType, len(payload), payload))
	}

	paeBytes := buildPAE("application/vnd.in-toto+json", stmtBytes)
	paeHash := sha256.Sum256(paeBytes)

	rSig, sSig, err := ecdsa.Sign(rand.Reader, privKey, paeHash[:])
	if err != nil {
		return fmt.Errorf("failed to sign PAE: %w", err)
	}
	sigASN1, err := asn1.Marshal(struct{ R, S *big.Int }{rSig, sSig})
	if err != nil {
		return fmt.Errorf("failed to marshal ECDSA signature: %w", err)
	}
	sigBase64 := base64.StdEncoding.EncodeToString(sigASN1)

	// Build DSSE JSON envelope compliant with cosign expectations.
	// We'll first build an envelope without the Rekor bundle, upload it to the
	// transparency log, then inject the returned bundle object (allowed because
	// it is outside the signed payload).
	signatures := []map[string]interface{}{ // using interface{} to allow raw JSON
		{
			"sig":  sigBase64,
			"cert": string(certPEM),
		},
	}
	envelope := map[string]interface{}{
		"payload":     base64.StdEncoding.EncodeToString(stmtBytes),
		"payloadType": "application/vnd.in-toto+json",
		"signatures":  signatures,
	}

	// Marshal the *unsigned* envelope to bytes for Rekor upload
	dsseUnsignedBytes, err := json.Marshal(envelope)
	if err != nil {
		return fmt.Errorf("failed to marshal DSSE envelope: %w", err)
	}

	// -------------------------------------------------------------
	// 3. Upload DSSE envelope to Rekor as an in-toto entry and build bundle
	// -------------------------------------------------------------
	rClient, err := getRekorClient("https://rekor.sigstore.dev")
	if err != nil {
		return fmt.Errorf("failed to create rekor client: %w", err)
	}

	// Upload the DSSE envelope to Rekor using the *DSSE* entry type (v001). The
	// verification logic in cosign extracts the signature from dsse_v001 and
	// will fail with "unsupported type" if we instead create an intoto_v001
	// entry. Switching to DSSE ensures `cosign verify-attestation` succeeds.
	logEntry, err := tlogUploadDSSE(ctx, rClient, dsseUnsignedBytes, certPEM)
	if err != nil {
		return fmt.Errorf("failed to upload attestation to Rekor: %w", err)
	}
	bundleJSON, _ := json.Marshal(cosignbundle.EntryToBundle(logEntry))

	// -------------------------------------------------------------
	// DO NOT mutate the envelope after it's been uploaded to Rekor.
	// The dsse_v001 entry stores a SHA-256 hash of the *entire*
	// envelope; any modification will cause cosign verification to
	// fail with a bundle/payload mismatch.  We therefore keep the
	// envelope exactly as-signed and carry the Rekor bundle only as a
	// layer annotation.
	// -------------------------------------------------------------
	dsseBytes := dsseUnsignedBytes

	// -------------------------------------------------------------
	// 4. Store DSSE envelope blob in DB
	// -------------------------------------------------------------
	envDigest := fmt.Sprintf("sha256:%x", sha256.Sum256(dsseBytes))
	if err := storeArtifactBlob(ctx, envDigest, "application/vnd.dsse.envelope.v1+json", dsseBytes); err != nil {
		return fmt.Errorf("failed to store DSSE envelope blob: %w", err)
	}

	// -------------------------------------------------------------
	// 5. Build and store OCI artifact manifest
	// -------------------------------------------------------------
	subjectDigest := "sha256:" + digest
	subjectBytes, _, err := getArtifactBlobByDigest(ctx, subjectDigest)
	if err != nil {
		return fmt.Errorf("failed to fetch subject manifest for size: %w", err)
	}
	subjectDesc := oci.Descriptor{
		MediaType: "application/vnd.oci.image.manifest.v1+json",
		Digest:    subjectDigest,
		Size:      int64(len(subjectBytes)),
	}

	// Extract the final signature (base64) from the fully-formed DSSE envelope so
	// that the annotation mirrors what CosignAttestWithCustomSubject() stores.
	signatureBase64, err := parseDSSEEnvelope(dsseBytes)
	if err != nil {
		return err
	}

	layerDesc := oci.Descriptor{
		MediaType: "application/vnd.dsse.envelope.v1+json",
		Digest:    envDigest,
		Size:      int64(len(dsseBytes)),
		Annotations: map[string]string{
			"dev.cosignproject.cosign/predicateType": statement.PredicateType,
			"dev.cosignproject.cosign/signature":     signatureBase64,
			"dev.sigstore.cosign/certificate":        string(certPEM),
			"dev.sigstore.cosign/bundle":             string(bundleJSON),
		},
	}

	manifestBytes, err := newOCIArtifactManifest(&subjectDesc, "application/vnd.in-toto+json", []oci.Descriptor{layerDesc}, nil)
	if err != nil {
		return fmt.Errorf("failed to build OCI artifact manifest: %w", err)
	}

	if err := storeFullArtifactManifest(ctx, manifestBytes, imageCatalogID, nil); err != nil {
		return fmt.Errorf("failed to store attestation artifact manifest: %w", err)
	}

	logger.Info("uploaded keyless attestation to local DB (OCI-compliant)",
		zap.String("subjectDigest", digest),
		zap.Int("manifestLength", len(manifestBytes)))

	return nil
}
